version: '3'
services:
  afisha_db:
    image: "postgres:12"
    environment:
      POSTGRES_USER: afisha_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: afisha_db
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  backend:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - afisha_db
volumes:
  postgres-data: